# Generated by Django 3.0.4 on 2020-03-13 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 3, 13, 14, 10, 22, 504468, tzinfo=utc))),
                ('category', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=10)),
            ],
        ),
    ]
