# Generated by Django 3.0.4 on 2020-03-13 15:16

from django.db import migrations
import trix.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200313_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=trix.fields.TrixField(verbose_name='Content'),
        ),
    ]
