# Generated by Django 3.0.4 on 2020-03-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200313_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_name',
        ),
    ]
