# Generated by Django 3.0.4 on 2020-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200314_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
