# Generated by Django 3.0.4 on 2020-03-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200314_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colour',
            field=models.CharField(choices=[('btn-outline-success', 'Green'), ('btn-outline-primary', 'Blue'), ('btn-outline-danger', 'Red'), ('btn-outline-warning', 'Yellow'), ('btn-outline-info', 'Cyan'), ('btn-outline-secondary', 'Grey'), ('btn-outline-dark', 'Black')], default='btn-outline-success', max_length=25),
        ),
    ]
