# Generated by Django 3.0.4 on 2020-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_category_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colour_outline',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.CharField(choices=[('success', 'Green'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('secondary', 'Grey'), ('dark', 'Black')], default='btn-outline-success', max_length=25),
        ),
    ]
